export const UI_STRINGS = {
  login: {
    title: 'Ville IA',
    subtitle: 'Connexion',
    usernameLabel: "Nom d'utilisateur",
    passwordLabel: 'Mot de passe',
    submitButton: 'Se connecter',
    submitButtonLoading: 'Connexion…',
    hint: 'Seuls les comptes créés par un administrateur peuvent se connecter.',
    errorEmpty: "Veuillez saisir un nom d'utilisateur et un mot de passe.",
    errorInvalid: "Nom d'utilisateur ou mot de passe incorrect.",
    errorGeneric: 'Erreur de connexion. Réessayez.',
  },
  adminUsers: {
    backLink: '← Carte',
    title: 'Gestion des utilisateurs',
    createAccount: 'Créer un compte',
    usernameLabel: "Nom d'utilisateur",
    passwordLabel: 'Mot de passe (min. 8 caractères)',
    emailLabel: 'Courriel',
    phoneLabel: 'Téléphone',
    emailPlaceholder: 'exemple@domaine.com',
    phonePlaceholder: '+1 514 555-1234',
    createButton: 'Créer le compte',
    createButtonLoading: 'Création…',
    existingAccounts: 'Comptes existants',
    loading: 'Chargement…',
    adminBadge: 'Admin',
    newPasswordPlaceholder: 'Nouveau mot de passe (min. 8 car.)',
    saveButton: 'Enregistrer',
    saveButtonLoading: 'Enregistrement…',
    cancelButton: 'Annuler',
    changePassword: 'Changer le mot de passe',
    editContact: 'Modifier courriel / téléphone',
    deleteButton: 'Supprimer',
    deleteButtonLoading: 'Suppression…',
    listEmpty: 'Aucun compte pour le moment.',
    errorUsernameRequired: "Indiquez un nom d'utilisateur.",
    errorPasswordMin: 'Le mot de passe doit contenir au moins 8 caractères.',
    errorEmailRequired: 'Indiquez une adresse courriel.',
    errorEmailInvalid: 'Adresse courriel invalide (ex. utilisateur@domaine.com).',
    errorPhoneRequired: 'Indiquez un numéro de téléphone.',
    errorPhoneInvalid:
      'Le numéro doit contenir entre 10 et 15 chiffres (ex. 5145551234 ou +1 514 555-1234).',
    errorPhoneInvalidShort: 'Le numéro doit contenir entre 10 et 15 chiffres.',
    successCreated: 'Compte créé avec succès.',
    errorTimeout: 'La création a pris trop de temps. Vérifiez que le serveur répond et réessayez.',
    errorInvalidData: 'Données invalides.',
    errorCreateGeneric: 'Erreur lors de la création du compte.',
    errorLoadList: 'Impossible de charger la liste des utilisateurs.',
    successContactUpdated: 'Courriel et téléphone mis à jour.',
    successPasswordUpdated: 'Mot de passe mis à jour.',
    successDeleted: 'Compte supprimé.',
    confirmDelete: (username: string) =>
      `Supprimer le compte « ${username} » ? Cette action est irréversible.`,
  },
  alertSettings: {
    backLink: '← Carte',
    title: "Paramètres d'alertes",
    subtitle:
      'Activez les scénarios qui vous intéressent et définissez un seuil pour chacun. Le courriel et le numéro de téléphone du compte sont utilisés pour toutes les alertes.',
    channelsIntro: 'Canaux et fréquence (communs à tous les scénarios)',
    loading: 'Chargement…',
    enableType: 'Activer les alertes pour ce scénario',
    pluvialTitle: 'Inondations pluviales',
    fluvialTitle: 'Crues (inondations fluviales)',
    heatwaveTitle: 'Canicules',
    snowTitle: 'Chutes de neige',
    thresholdPluvialLabel: 'Seuil — risque pluvial affiché sur la carte (%)',
    thresholdFluvialLabel: 'Seuil — probabilité de crue (%)',
    thresholdHeatwaveLabel: 'Seuil — humidex maximal prévu',
    thresholdSnowLabel: 'Seuil — risque de neige (%)',
    frequencyLabel: "Fréquence d'envoi par scénario (heures)",
    frequencyHint:
      'Entre 4 et 24 h. Pour chaque type d’alerte activé, au plus un message pendant cette période si le seuil est dépassé.',
    alertsViaSms: 'Recevoir les alertes par SMS',
    alertsViaEmail: 'Recevoir les alertes par email',
    saveButton: 'Enregistrer',
    saveButtonLoading: 'Enregistrement…',
    testSmsButton: 'Envoyer un SMS de test',
    testSmsButtonLoading: 'Envoi…',
    testEmailButton: 'Envoyer un email de test',
    testEmailButtonLoading: 'Envoi…',
    errorLoad: "Impossible de charger les paramètres d'alertes.",
    successSaved: 'Paramètres enregistrés.',
    errorSave: "Erreur lors de l'enregistrement.",
    errorNoPhone: 'Aucun numéro de téléphone enregistré.',
    errorNoEmail: 'Aucune adresse courriel enregistrée.',
    successTestSms: 'SMS de test envoyé.',
    errorTestSms: 'Envoi du SMS de test impossible.',
    successTestEmail: 'Email de test envoyé.',
    errorTestEmail: "Envoi de l'email de test impossible.",
  },
  journalReport: {
    backLink: '← Carte',
    title: "Rapport d'analyse",
    subtitle:
      'Sélectionnez la période de journalisation à analyser. Le rapport est généré à partir de vos actions sur la carte et l’interface. Un fichier PDF est téléchargé automatiquement.',
    dateFromLabel: 'Date de début (incluse)',
    dateToLabel: 'Date de fin (incluse)',
    maxEntriesLabel: 'Nombre maximal d’entrées',
    maxEntriesHint: 'Entre 10 et 2000. Les entrées les plus récentes sont retenues.',
    includeActionLogsLabel:
      'Afficher dans le PDF la synthèse d’usage, l’activité et le journal détaillé',
    includeActionLogsHint:
      'L’analyse (faits saillants, synthèse, etc.) utilise toujours tout le journal côté serveur. Décochez uniquement pour masquer ces sections « logs » dans le fichier PDF.',
    includeModelDataSectionsLabel: 'Afficher dans le PDF la section données / requêtes modèles',
    includeModelDataSectionsHint:
      'L’analyse utilise toujours l’ensemble des traces. Décochez pour masquer dans le PDF la section sur les données utilisées par les modèles.',
    generateButton: 'Générer le rapport',
    generateButtonLoading: 'Génération…',
    errorDates: 'La date de début doit être antérieure ou égale à la date de fin.',
    errorGenerate: 'Impossible de générer le rapport.',
    errorPdf:
      'Le téléchargement du PDF a échoué. Réessayez ou vérifiez que votre navigateur autorise les téléchargements pour ce site.',
    sectionMetadata: '1. Métadonnées du rapport',
    sectionSubjectIdentity: "2. Identité et contexte de l'utilisateur",
    sectionHighRisk: '3. Faits saillants (risques)',
    sectionRecommendations:
      '4. Recommandations (territoires / indicateurs météo, sociaux, territoriaux)',
    sectionSummary: '5. Synthèse exécutive',
    sectionPeriod: 'Période et entrées analysées (journal)',
    sectionUsageOverview: "6. Synthèse de l'utilisation",
    sectionActivity: "7. Observations sur l'activité",
    sectionDetailedEvents: '8. Journal détaillé des événements',
    sectionModelData: '9. Données utilisées par les modèles',
    emptyList: '—',
    emptyEvents: 'Aucun événement détaillé pour cette période.',
  },
} as const;
