export const LOGIN_STRINGS = {
  LOGO_ALT: "IRIU - Institut de la résilience et de l'innovation urbaine",
  TITLE: 'Ville IA',
  SUBTITLE: 'Connexion',
  USERNAME_LABEL: "Nom d'utilisateur",
  PASSWORD_LABEL: 'Mot de passe',
  SUBMIT_BUTTON: 'Se connecter',
  SUBMIT_BUTTON_LOADING: 'Connexion…',
  HINT: 'Seuls les comptes créés par un administrateur peuvent se connecter.',
  ERROR_EMPTY: "Nom d'utilisateur et mot de passe requis.",
  ERROR_INVALID: "Nom d'utilisateur ou mot de passe incorrect.",
  ERROR_GENERIC: 'Une erreur est survenue. Réessayez.',
} as const;

export const SERVER_INVALID_CREDENTIALS_FR = "Nom d'utilisateur ou mot de passe invalide.";

export const ADMIN_USERS_STRINGS = {
  BACK_LINK: '← Carte',
  TITLE: 'Gestion des utilisateurs',
  CREATE_ACCOUNT: 'Créer un compte',
  USERNAME_LABEL: "Nom d'utilisateur",
  PASSWORD_LABEL: 'Mot de passe (min. 8 caractères)',
  EMAIL_LABEL: 'Courriel',
  PHONE_LABEL: 'Téléphone',
  EMAIL_PLACEHOLDER: 'exemple@domaine.com',
  PHONE_PLACEHOLDER: '+1 514 555-1234',
  PARTNER_CITY_LABEL: 'Ville partenaire',
  PARTNER_CITY_MONTREAL: 'Montréal',
  PARTNER_CITY_LAVAL: 'Laval',
  PARTNER_CITY_SHORT: 'Ville',
  EDIT_PARTNER_CITY: 'Modifier la ville',
  CREATE_BUTTON: 'Créer le compte',
  CREATE_BUTTON_LOADING: 'Création…',
  EXISTING_ACCOUNTS: 'Comptes existants',
  LOADING: 'Chargement…',
  ADMIN_BADGE: 'Admin',
  NEW_PASSWORD_PLACEHOLDER: 'Nouveau mot de passe (min. 8 car.)',
  SAVE_BUTTON: 'Enregistrer',
  SAVE_BUTTON_LOADING: 'Enregistrement…',
  CANCEL_BUTTON: 'Annuler',
  CHANGE_PASSWORD: 'Changer le mot de passe',
  EDIT_CONTACT: 'Modifier courriel / téléphone',
  DELETE_BUTTON: 'Supprimer',
  DELETE_BUTTON_LOADING: 'Suppression…',
  VIEW_LOGS: 'Voir les logs',
  HIDE_LOGS: 'Masquer les logs',
  LOGS_TITLE: 'Historique des actions',
  LOGS_FILTER_DATE: 'Date (YYYY-MM-DD)',
  LOGS_FILTER_LIMIT: 'Nombre max',
  LOGS_LOAD_BUTTON: 'Charger',
  LOGS_LOADING: 'Chargement des logs…',
  LOGS_EMPTY: 'Aucun log pour ce filtre.',
  LOGS_ERROR: 'Impossible de charger les logs utilisateur.',
  LOGS_COLUMN_TIME: 'Date/heure',
  LOGS_COLUMN_ACTION: 'Action',
  LOGS_COLUMN_LABEL: 'Détail',
  LOGS_COLUMN_ROUTE: 'Route',
  LOGS_COLUMN_PAYLOAD: 'Payload modèle',
  LIST_EMPTY: 'Aucun compte pour le moment.',
  ERROR_LOAD_LIST: 'Impossible de charger la liste des utilisateurs.',
  ERROR_INVALID_DATA: 'Réponse invalide du serveur.',
  ERROR_CREATE_GENERIC: 'Impossible de créer le compte.',
  ERROR_USERNAME_REQUIRED: 'Le nom d’utilisateur est requis.',
  ERROR_PASSWORD_MIN: 'Le mot de passe doit contenir au moins 8 caractères.',
  ERROR_EMAIL_REQUIRED: 'Le courriel est requis.',
  ERROR_EMAIL_INVALID: 'Le courriel n’est pas valide.',
  ERROR_PHONE_REQUIRED: 'Le téléphone est requis.',
  ERROR_PHONE_INVALID: 'Le numéro de téléphone n’est pas valide.',
  ERROR_PHONE_INVALID_SHORT: 'Le numéro de téléphone doit contenir entre 10 et 15 chiffres.',
  ERROR_TIMEOUT: 'La requête a expiré. Réessayez.',
  SUCCESS_CREATED: 'Compte créé avec succès.',
  SUCCESS_CONTACT_UPDATED: 'Courriel et téléphone mis à jour.',
  SUCCESS_PARTNER_CITY_UPDATED: 'Ville partenaire mise à jour.',
  SUCCESS_PASSWORD_UPDATED: 'Mot de passe mis à jour.',
  SUCCESS_DELETED: 'Utilisateur supprimé.',
  CONFIRM_DELETE: "Supprimer l'utilisateur « {username} » ?",
} as const;
